spring.application.name=Banking
spring.datasource.url=jdbc:postgresql://localhost:5432/banking
spring.datasource.username=postgres
spring.datasource.password=123321
#logging.level.org.flywaydb=DEBUG
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
